import { put } from '@vercel/blob'

/**
 * Persist generated bytes and return a URL the browser can load.
 *
 * Vercel Blob when configured. Without a token it falls back to an inline data
 * URL so the pipeline is runnable locally before storage is provisioned. The
 * fallback is not for production: it puts ~1.4x the image size in Postgres.
 */
export async function putImage(bytes: Buffer, mime: string, key: string): Promise<string> {
  if (process.env.BLOB_READ_WRITE_TOKEN) {
    const ext = mime.includes('png') ? 'png' : 'jpg'
    const { url } = await put(`generations/${key}.${ext}`, bytes, {
      access: 'public',
      contentType: mime,
      addRandomSuffix: false,
    })
    return url
  }

  console.warn('[storage] BLOB_READ_WRITE_TOKEN missing — inlining as a data URL (dev only)')
  return `data:${mime};base64,${bytes.toString('base64')}`
}
